AGENT_TEMPLATES = [
    {
        "name": "PM",
        "description": "Project Manager — coordinates work, delegates tasks, never touches code.",
        "agent_type": "pm",
        "model": "claude-sonnet-4-6",
        "dangerously_skip_permissions": True,
        "plan_mode": True,
        "flags": {},
    },
    {
        "name": "Software Engineer",
        "description": "Creates worktrees, implements features, opens PRs, reports back to PM.",
        "agent_type": "software_engineer",
        "model": "claude-sonnet-4-6",
        "dangerously_skip_permissions": True,
        "plan_mode": False,
        "flags": {},
    },
    {
        "name": "QA",
        "description": "Checks out branches, runs tests, browser tests, reports pass/fail and bugs to PM.",
        "agent_type": "qa",
        "model": "claude-sonnet-4-6",
        "dangerously_skip_permissions": True,
        "plan_mode": False,
        "flags": {},
    },
    {
        "name": "Full Auto",
        "description": "Software Engineer with --dangerously-skip-permissions — no permission prompts.",
        "agent_type": "software_engineer",
        "model": "claude-sonnet-4-6",
        "dangerously_skip_permissions": True,
        "plan_mode": False,
        "flags": {},
    },
    {
        "name": "Planner",
        "description": "Read-only planning mode — analyses and proposes but never modifies files.",
        "agent_type": "custom",
        "model": "claude-sonnet-4-6",
        "dangerously_skip_permissions": False,
        "plan_mode": True,
        "flags": {},
    },
]
